# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/hydra/hydra

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/hydra/hydra/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/runner/work/hydra/hydra/build/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/hydra/hydra/build/CMakeFiles /home/runner/work/hydra/hydra/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/hydra/hydra/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hydra

# Build rule for target.
hydra: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hydra
.PHONY : hydra

# fast build rule for target.
hydra/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/build
.PHONY : hydra/fast

#=============================================================================
# Target rules for targets named hydra_images

# Build rule for target.
hydra_images: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hydra_images
.PHONY : hydra_images

# fast build rule for target.
hydra_images/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_images.dir/build.make CMakeFiles/hydra_images.dir/build
.PHONY : hydra_images/fast

#=============================================================================
# Target rules for targets named hydra_other

# Build rule for target.
hydra_other: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hydra_other
.PHONY : hydra_other

# fast build rule for target.
hydra_other/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_other.dir/build.make CMakeFiles/hydra_other.dir/build
.PHONY : hydra_other/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f vendored/fmt/CMakeFiles/fmt.dir/build.make vendored/fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named argparse

# Build rule for target.
argparse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 argparse
.PHONY : argparse

# fast build rule for target.
argparse/fast:
	$(MAKE) $(MAKESILENT) -f vendored/argparse/CMakeFiles/argparse.dir/build.make vendored/argparse/CMakeFiles/argparse.dir/build
.PHONY : argparse/fast

#=============================================================================
# Target rules for targets named SDL3-static

# Build rule for target.
SDL3-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3-static
.PHONY : SDL3-static

# fast build rule for target.
SDL3-static/fast:
	$(MAKE) $(MAKESILENT) -f vendored/SDL/CMakeFiles/SDL3-static.dir/build.make vendored/SDL/CMakeFiles/SDL3-static.dir/build
.PHONY : SDL3-static/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f vendored/SDL/CMakeFiles/uninstall.dir/build.make vendored/SDL/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named crypto

# Build rule for target.
crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crypto
.PHONY : crypto

# fast build rule for target.
crypto/fast:
	$(MAKE) $(MAKESILENT) -f vendored/openssl/crypto/CMakeFiles/crypto.dir/build.make vendored/openssl/crypto/CMakeFiles/crypto.dir/build
.PHONY : crypto/fast

#=============================================================================
# Target rules for targets named ssl

# Build rule for target.
ssl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ssl
.PHONY : ssl

# fast build rule for target.
ssl/fast:
	$(MAKE) $(MAKESILENT) -f vendored/openssl/ssl/CMakeFiles/ssl.dir/build.make vendored/openssl/ssl/CMakeFiles/ssl.dir/build
.PHONY : ssl/fast

__cmrc_hydra_images/intermediate/images/hydra.png.o: __cmrc_hydra_images/intermediate/images/hydra.png.cpp.o
.PHONY : __cmrc_hydra_images/intermediate/images/hydra.png.o

# target to build an object file
__cmrc_hydra_images/intermediate/images/hydra.png.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_images.dir/build.make CMakeFiles/hydra_images.dir/__cmrc_hydra_images/intermediate/images/hydra.png.cpp.o
.PHONY : __cmrc_hydra_images/intermediate/images/hydra.png.cpp.o

__cmrc_hydra_images/intermediate/images/hydra.png.i: __cmrc_hydra_images/intermediate/images/hydra.png.cpp.i
.PHONY : __cmrc_hydra_images/intermediate/images/hydra.png.i

# target to preprocess a source file
__cmrc_hydra_images/intermediate/images/hydra.png.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_images.dir/build.make CMakeFiles/hydra_images.dir/__cmrc_hydra_images/intermediate/images/hydra.png.cpp.i
.PHONY : __cmrc_hydra_images/intermediate/images/hydra.png.cpp.i

__cmrc_hydra_images/intermediate/images/hydra.png.s: __cmrc_hydra_images/intermediate/images/hydra.png.cpp.s
.PHONY : __cmrc_hydra_images/intermediate/images/hydra.png.s

# target to generate assembly for a file
__cmrc_hydra_images/intermediate/images/hydra.png.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_images.dir/build.make CMakeFiles/hydra_images.dir/__cmrc_hydra_images/intermediate/images/hydra.png.cpp.s
.PHONY : __cmrc_hydra_images/intermediate/images/hydra.png.cpp.s

__cmrc_hydra_images/lib.o: __cmrc_hydra_images/lib.cpp.o
.PHONY : __cmrc_hydra_images/lib.o

# target to build an object file
__cmrc_hydra_images/lib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_images.dir/build.make CMakeFiles/hydra_images.dir/__cmrc_hydra_images/lib.cpp.o
.PHONY : __cmrc_hydra_images/lib.cpp.o

__cmrc_hydra_images/lib.i: __cmrc_hydra_images/lib.cpp.i
.PHONY : __cmrc_hydra_images/lib.i

# target to preprocess a source file
__cmrc_hydra_images/lib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_images.dir/build.make CMakeFiles/hydra_images.dir/__cmrc_hydra_images/lib.cpp.i
.PHONY : __cmrc_hydra_images/lib.cpp.i

__cmrc_hydra_images/lib.s: __cmrc_hydra_images/lib.cpp.s
.PHONY : __cmrc_hydra_images/lib.s

# target to generate assembly for a file
__cmrc_hydra_images/lib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_images.dir/build.make CMakeFiles/hydra_images.dir/__cmrc_hydra_images/lib.cpp.s
.PHONY : __cmrc_hydra_images/lib.cpp.s

__cmrc_hydra_other/intermediate/other/cacert.pem.o: __cmrc_hydra_other/intermediate/other/cacert.pem.cpp.o
.PHONY : __cmrc_hydra_other/intermediate/other/cacert.pem.o

# target to build an object file
__cmrc_hydra_other/intermediate/other/cacert.pem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_other.dir/build.make CMakeFiles/hydra_other.dir/__cmrc_hydra_other/intermediate/other/cacert.pem.cpp.o
.PHONY : __cmrc_hydra_other/intermediate/other/cacert.pem.cpp.o

__cmrc_hydra_other/intermediate/other/cacert.pem.i: __cmrc_hydra_other/intermediate/other/cacert.pem.cpp.i
.PHONY : __cmrc_hydra_other/intermediate/other/cacert.pem.i

# target to preprocess a source file
__cmrc_hydra_other/intermediate/other/cacert.pem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_other.dir/build.make CMakeFiles/hydra_other.dir/__cmrc_hydra_other/intermediate/other/cacert.pem.cpp.i
.PHONY : __cmrc_hydra_other/intermediate/other/cacert.pem.cpp.i

__cmrc_hydra_other/intermediate/other/cacert.pem.s: __cmrc_hydra_other/intermediate/other/cacert.pem.cpp.s
.PHONY : __cmrc_hydra_other/intermediate/other/cacert.pem.s

# target to generate assembly for a file
__cmrc_hydra_other/intermediate/other/cacert.pem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_other.dir/build.make CMakeFiles/hydra_other.dir/__cmrc_hydra_other/intermediate/other/cacert.pem.cpp.s
.PHONY : __cmrc_hydra_other/intermediate/other/cacert.pem.cpp.s

__cmrc_hydra_other/lib.o: __cmrc_hydra_other/lib.cpp.o
.PHONY : __cmrc_hydra_other/lib.o

# target to build an object file
__cmrc_hydra_other/lib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_other.dir/build.make CMakeFiles/hydra_other.dir/__cmrc_hydra_other/lib.cpp.o
.PHONY : __cmrc_hydra_other/lib.cpp.o

__cmrc_hydra_other/lib.i: __cmrc_hydra_other/lib.cpp.i
.PHONY : __cmrc_hydra_other/lib.i

# target to preprocess a source file
__cmrc_hydra_other/lib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_other.dir/build.make CMakeFiles/hydra_other.dir/__cmrc_hydra_other/lib.cpp.i
.PHONY : __cmrc_hydra_other/lib.cpp.i

__cmrc_hydra_other/lib.s: __cmrc_hydra_other/lib.cpp.s
.PHONY : __cmrc_hydra_other/lib.s

# target to generate assembly for a file
__cmrc_hydra_other/lib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra_other.dir/build.make CMakeFiles/hydra_other.dir/__cmrc_hydra_other/lib.cpp.s
.PHONY : __cmrc_hydra_other/lib.cpp.s

src/app.o: src/app.cxx.o
.PHONY : src/app.o

# target to build an object file
src/app.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/app.cxx.o
.PHONY : src/app.cxx.o

src/app.i: src/app.cxx.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/app.cxx.i
.PHONY : src/app.cxx.i

src/app.s: src/app.cxx.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/app.cxx.s
.PHONY : src/app.cxx.s

src/corewrapper.o: src/corewrapper.cxx.o
.PHONY : src/corewrapper.o

# target to build an object file
src/corewrapper.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/corewrapper.cxx.o
.PHONY : src/corewrapper.cxx.o

src/corewrapper.i: src/corewrapper.cxx.i
.PHONY : src/corewrapper.i

# target to preprocess a source file
src/corewrapper.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/corewrapper.cxx.i
.PHONY : src/corewrapper.cxx.i

src/corewrapper.s: src/corewrapper.cxx.s
.PHONY : src/corewrapper.s

# target to generate assembly for a file
src/corewrapper.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/corewrapper.cxx.s
.PHONY : src/corewrapper.cxx.s

src/gamewindow.o: src/gamewindow.cxx.o
.PHONY : src/gamewindow.o

# target to build an object file
src/gamewindow.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/gamewindow.cxx.o
.PHONY : src/gamewindow.cxx.o

src/gamewindow.i: src/gamewindow.cxx.i
.PHONY : src/gamewindow.i

# target to preprocess a source file
src/gamewindow.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/gamewindow.cxx.i
.PHONY : src/gamewindow.cxx.i

src/gamewindow.s: src/gamewindow.cxx.s
.PHONY : src/gamewindow.s

# target to generate assembly for a file
src/gamewindow.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/gamewindow.cxx.s
.PHONY : src/gamewindow.cxx.s

src/main.o: src/main.cxx.o
.PHONY : src/main.o

# target to build an object file
src/main.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/main.cxx.o
.PHONY : src/main.cxx.o

src/main.i: src/main.cxx.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/main.cxx.i
.PHONY : src/main.cxx.i

src/main.s: src/main.cxx.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/main.cxx.s
.PHONY : src/main.cxx.s

src/mainwindow.o: src/mainwindow.cxx.o
.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/mainwindow.cxx.o
.PHONY : src/mainwindow.cxx.o

src/mainwindow.i: src/mainwindow.cxx.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/mainwindow.cxx.i
.PHONY : src/mainwindow.cxx.i

src/mainwindow.s: src/mainwindow.cxx.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/src/mainwindow.cxx.s
.PHONY : src/mainwindow.cxx.s

vendored/argparse/argparse.o: vendored/argparse/argparse.c.o
.PHONY : vendored/argparse/argparse.o

# target to build an object file
vendored/argparse/argparse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/argparse/argparse.c.o
.PHONY : vendored/argparse/argparse.c.o

vendored/argparse/argparse.i: vendored/argparse/argparse.c.i
.PHONY : vendored/argparse/argparse.i

# target to preprocess a source file
vendored/argparse/argparse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/argparse/argparse.c.i
.PHONY : vendored/argparse/argparse.c.i

vendored/argparse/argparse.s: vendored/argparse/argparse.c.s
.PHONY : vendored/argparse/argparse.s

# target to generate assembly for a file
vendored/argparse/argparse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/argparse/argparse.c.s
.PHONY : vendored/argparse/argparse.c.s

vendored/courier_prime.o: vendored/courier_prime.cxx.o
.PHONY : vendored/courier_prime.o

# target to build an object file
vendored/courier_prime.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/courier_prime.cxx.o
.PHONY : vendored/courier_prime.cxx.o

vendored/courier_prime.i: vendored/courier_prime.cxx.i
.PHONY : vendored/courier_prime.i

# target to preprocess a source file
vendored/courier_prime.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/courier_prime.cxx.i
.PHONY : vendored/courier_prime.cxx.i

vendored/courier_prime.s: vendored/courier_prime.cxx.s
.PHONY : vendored/courier_prime.s

# target to generate assembly for a file
vendored/courier_prime.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/courier_prime.cxx.s
.PHONY : vendored/courier_prime.cxx.s

vendored/glad/src/glad.o: vendored/glad/src/glad.c.o
.PHONY : vendored/glad/src/glad.o

# target to build an object file
vendored/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/glad/src/glad.c.o
.PHONY : vendored/glad/src/glad.c.o

vendored/glad/src/glad.i: vendored/glad/src/glad.c.i
.PHONY : vendored/glad/src/glad.i

# target to preprocess a source file
vendored/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/glad/src/glad.c.i
.PHONY : vendored/glad/src/glad.c.i

vendored/glad/src/glad.s: vendored/glad/src/glad.c.s
.PHONY : vendored/glad/src/glad.s

# target to generate assembly for a file
vendored/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/glad/src/glad.c.s
.PHONY : vendored/glad/src/glad.c.s

vendored/imgui/backends/imgui_impl_opengl3.o: vendored/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : vendored/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
vendored/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : vendored/imgui/backends/imgui_impl_opengl3.cpp.o

vendored/imgui/backends/imgui_impl_opengl3.i: vendored/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : vendored/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
vendored/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : vendored/imgui/backends/imgui_impl_opengl3.cpp.i

vendored/imgui/backends/imgui_impl_opengl3.s: vendored/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : vendored/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
vendored/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : vendored/imgui/backends/imgui_impl_opengl3.cpp.s

vendored/imgui/backends/imgui_impl_sdl3.o: vendored/imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : vendored/imgui/backends/imgui_impl_sdl3.o

# target to build an object file
vendored/imgui/backends/imgui_impl_sdl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : vendored/imgui/backends/imgui_impl_sdl3.cpp.o

vendored/imgui/backends/imgui_impl_sdl3.i: vendored/imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : vendored/imgui/backends/imgui_impl_sdl3.i

# target to preprocess a source file
vendored/imgui/backends/imgui_impl_sdl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : vendored/imgui/backends/imgui_impl_sdl3.cpp.i

vendored/imgui/backends/imgui_impl_sdl3.s: vendored/imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : vendored/imgui/backends/imgui_impl_sdl3.s

# target to generate assembly for a file
vendored/imgui/backends/imgui_impl_sdl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : vendored/imgui/backends/imgui_impl_sdl3.cpp.s

vendored/imgui/imgui.o: vendored/imgui/imgui.cpp.o
.PHONY : vendored/imgui/imgui.o

# target to build an object file
vendored/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui.cpp.o
.PHONY : vendored/imgui/imgui.cpp.o

vendored/imgui/imgui.i: vendored/imgui/imgui.cpp.i
.PHONY : vendored/imgui/imgui.i

# target to preprocess a source file
vendored/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui.cpp.i
.PHONY : vendored/imgui/imgui.cpp.i

vendored/imgui/imgui.s: vendored/imgui/imgui.cpp.s
.PHONY : vendored/imgui/imgui.s

# target to generate assembly for a file
vendored/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui.cpp.s
.PHONY : vendored/imgui/imgui.cpp.s

vendored/imgui/imgui_demo.o: vendored/imgui/imgui_demo.cpp.o
.PHONY : vendored/imgui/imgui_demo.o

# target to build an object file
vendored/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_demo.cpp.o
.PHONY : vendored/imgui/imgui_demo.cpp.o

vendored/imgui/imgui_demo.i: vendored/imgui/imgui_demo.cpp.i
.PHONY : vendored/imgui/imgui_demo.i

# target to preprocess a source file
vendored/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_demo.cpp.i
.PHONY : vendored/imgui/imgui_demo.cpp.i

vendored/imgui/imgui_demo.s: vendored/imgui/imgui_demo.cpp.s
.PHONY : vendored/imgui/imgui_demo.s

# target to generate assembly for a file
vendored/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_demo.cpp.s
.PHONY : vendored/imgui/imgui_demo.cpp.s

vendored/imgui/imgui_draw.o: vendored/imgui/imgui_draw.cpp.o
.PHONY : vendored/imgui/imgui_draw.o

# target to build an object file
vendored/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_draw.cpp.o
.PHONY : vendored/imgui/imgui_draw.cpp.o

vendored/imgui/imgui_draw.i: vendored/imgui/imgui_draw.cpp.i
.PHONY : vendored/imgui/imgui_draw.i

# target to preprocess a source file
vendored/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_draw.cpp.i
.PHONY : vendored/imgui/imgui_draw.cpp.i

vendored/imgui/imgui_draw.s: vendored/imgui/imgui_draw.cpp.s
.PHONY : vendored/imgui/imgui_draw.s

# target to generate assembly for a file
vendored/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_draw.cpp.s
.PHONY : vendored/imgui/imgui_draw.cpp.s

vendored/imgui/imgui_tables.o: vendored/imgui/imgui_tables.cpp.o
.PHONY : vendored/imgui/imgui_tables.o

# target to build an object file
vendored/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_tables.cpp.o
.PHONY : vendored/imgui/imgui_tables.cpp.o

vendored/imgui/imgui_tables.i: vendored/imgui/imgui_tables.cpp.i
.PHONY : vendored/imgui/imgui_tables.i

# target to preprocess a source file
vendored/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_tables.cpp.i
.PHONY : vendored/imgui/imgui_tables.cpp.i

vendored/imgui/imgui_tables.s: vendored/imgui/imgui_tables.cpp.s
.PHONY : vendored/imgui/imgui_tables.s

# target to generate assembly for a file
vendored/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_tables.cpp.s
.PHONY : vendored/imgui/imgui_tables.cpp.s

vendored/imgui/imgui_widgets.o: vendored/imgui/imgui_widgets.cpp.o
.PHONY : vendored/imgui/imgui_widgets.o

# target to build an object file
vendored/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_widgets.cpp.o
.PHONY : vendored/imgui/imgui_widgets.cpp.o

vendored/imgui/imgui_widgets.i: vendored/imgui/imgui_widgets.cpp.i
.PHONY : vendored/imgui/imgui_widgets.i

# target to preprocess a source file
vendored/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_widgets.cpp.i
.PHONY : vendored/imgui/imgui_widgets.cpp.i

vendored/imgui/imgui_widgets.s: vendored/imgui/imgui_widgets.cpp.s
.PHONY : vendored/imgui/imgui_widgets.s

# target to generate assembly for a file
vendored/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/imgui/imgui_widgets.cpp.s
.PHONY : vendored/imgui/imgui_widgets.cpp.s

vendored/miniaudio.o: vendored/miniaudio.c.o
.PHONY : vendored/miniaudio.o

# target to build an object file
vendored/miniaudio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/miniaudio.c.o
.PHONY : vendored/miniaudio.c.o

vendored/miniaudio.i: vendored/miniaudio.c.i
.PHONY : vendored/miniaudio.i

# target to preprocess a source file
vendored/miniaudio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/miniaudio.c.i
.PHONY : vendored/miniaudio.c.i

vendored/miniaudio.s: vendored/miniaudio.c.s
.PHONY : vendored/miniaudio.s

# target to generate assembly for a file
vendored/miniaudio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/miniaudio.c.s
.PHONY : vendored/miniaudio.c.s

vendored/miniz/miniz.o: vendored/miniz/miniz.c.o
.PHONY : vendored/miniz/miniz.o

# target to build an object file
vendored/miniz/miniz.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/miniz/miniz.c.o
.PHONY : vendored/miniz/miniz.c.o

vendored/miniz/miniz.i: vendored/miniz/miniz.c.i
.PHONY : vendored/miniz/miniz.i

# target to preprocess a source file
vendored/miniz/miniz.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/miniz/miniz.c.i
.PHONY : vendored/miniz/miniz.c.i

vendored/miniz/miniz.s: vendored/miniz/miniz.c.s
.PHONY : vendored/miniz/miniz.s

# target to generate assembly for a file
vendored/miniz/miniz.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/miniz/miniz.c.s
.PHONY : vendored/miniz/miniz.c.s

vendored/stb_image_write.o: vendored/stb_image_write.c.o
.PHONY : vendored/stb_image_write.o

# target to build an object file
vendored/stb_image_write.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/stb_image_write.c.o
.PHONY : vendored/stb_image_write.c.o

vendored/stb_image_write.i: vendored/stb_image_write.c.i
.PHONY : vendored/stb_image_write.i

# target to preprocess a source file
vendored/stb_image_write.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/stb_image_write.c.i
.PHONY : vendored/stb_image_write.c.i

vendored/stb_image_write.s: vendored/stb_image_write.c.s
.PHONY : vendored/stb_image_write.s

# target to generate assembly for a file
vendored/stb_image_write.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hydra.dir/build.make CMakeFiles/hydra.dir/vendored/stb_image_write.c.s
.PHONY : vendored/stb_image_write.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... SDL3-static"
	@echo "... argparse"
	@echo "... crypto"
	@echo "... fmt"
	@echo "... hydra"
	@echo "... hydra_images"
	@echo "... hydra_other"
	@echo "... ssl"
	@echo "... __cmrc_hydra_images/intermediate/images/hydra.png.o"
	@echo "... __cmrc_hydra_images/intermediate/images/hydra.png.i"
	@echo "... __cmrc_hydra_images/intermediate/images/hydra.png.s"
	@echo "... __cmrc_hydra_images/lib.o"
	@echo "... __cmrc_hydra_images/lib.i"
	@echo "... __cmrc_hydra_images/lib.s"
	@echo "... __cmrc_hydra_other/intermediate/other/cacert.pem.o"
	@echo "... __cmrc_hydra_other/intermediate/other/cacert.pem.i"
	@echo "... __cmrc_hydra_other/intermediate/other/cacert.pem.s"
	@echo "... __cmrc_hydra_other/lib.o"
	@echo "... __cmrc_hydra_other/lib.i"
	@echo "... __cmrc_hydra_other/lib.s"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/corewrapper.o"
	@echo "... src/corewrapper.i"
	@echo "... src/corewrapper.s"
	@echo "... src/gamewindow.o"
	@echo "... src/gamewindow.i"
	@echo "... src/gamewindow.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... vendored/argparse/argparse.o"
	@echo "... vendored/argparse/argparse.i"
	@echo "... vendored/argparse/argparse.s"
	@echo "... vendored/courier_prime.o"
	@echo "... vendored/courier_prime.i"
	@echo "... vendored/courier_prime.s"
	@echo "... vendored/glad/src/glad.o"
	@echo "... vendored/glad/src/glad.i"
	@echo "... vendored/glad/src/glad.s"
	@echo "... vendored/imgui/backends/imgui_impl_opengl3.o"
	@echo "... vendored/imgui/backends/imgui_impl_opengl3.i"
	@echo "... vendored/imgui/backends/imgui_impl_opengl3.s"
	@echo "... vendored/imgui/backends/imgui_impl_sdl3.o"
	@echo "... vendored/imgui/backends/imgui_impl_sdl3.i"
	@echo "... vendored/imgui/backends/imgui_impl_sdl3.s"
	@echo "... vendored/imgui/imgui.o"
	@echo "... vendored/imgui/imgui.i"
	@echo "... vendored/imgui/imgui.s"
	@echo "... vendored/imgui/imgui_demo.o"
	@echo "... vendored/imgui/imgui_demo.i"
	@echo "... vendored/imgui/imgui_demo.s"
	@echo "... vendored/imgui/imgui_draw.o"
	@echo "... vendored/imgui/imgui_draw.i"
	@echo "... vendored/imgui/imgui_draw.s"
	@echo "... vendored/imgui/imgui_tables.o"
	@echo "... vendored/imgui/imgui_tables.i"
	@echo "... vendored/imgui/imgui_tables.s"
	@echo "... vendored/imgui/imgui_widgets.o"
	@echo "... vendored/imgui/imgui_widgets.i"
	@echo "... vendored/imgui/imgui_widgets.s"
	@echo "... vendored/miniaudio.o"
	@echo "... vendored/miniaudio.i"
	@echo "... vendored/miniaudio.s"
	@echo "... vendored/miniz/miniz.o"
	@echo "... vendored/miniz/miniz.i"
	@echo "... vendored/miniz/miniz.s"
	@echo "... vendored/stb_image_write.o"
	@echo "... vendored/stb_image_write.i"
	@echo "... vendored/stb_image_write.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

